### PR TITLE
Hierarchy docstring

### PR DESCRIPTION
**Pull request by reed-foster**
#48

### CODE REVIEW

**Review by audrey01mit — APPROVED** [review]
Thank you that is great! Though the issue raised the following question: as for the other modules, where to add a general description of what is in devices? How to include a general description? ( I have a few ideas, like adding it in a `_description.py` file and calling it in `generate_api.py`, but still have to implement it.) It is not critical at all since `devices` speaks for itself I think, but if the hierarchy was to be extended, I need to provide a way to add a module description.

image

In any case, this is approved! (but please let the issue open)

**Comment by reed-foster** [comment]
I believe we can add an `__init__.py` file underneath the `devices/` directory with a docstring and it should add the docstring to the devices section

**Comment by audrey01mit** [comment]
yes haha that's why I created the issue I think...

**Review by audrey01mit — APPROVED** [review]
perfect thanks Reed!

**Pull request merged**
